//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBackupManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VBackupManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving path.
        /// </summary>
        public static string Archiving_path {
            get {
                return ResourceManager.GetString("Archiving_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup comment.
        /// </summary>
        public static string Backup_comment {
            get {
                return ResourceManager.GetString("Backup_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file &apos;{0}&apos; not found..
        /// </summary>
        public static string Backup_file___0___not_found_ {
            get {
                return ResourceManager.GetString("Backup file \'{0}\' not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup job is active.
        /// </summary>
        public static string Backup_job_is_active {
            get {
                return ResourceManager.GetString("Backup_job_is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup was created at {0}.
        /// </summary>
        public static string Backup_was_created_at__0_ {
            get {
                return ResourceManager.GetString("Backup was created at {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups History.
        /// </summary>
        public static string Backups_History {
            get {
                return ResourceManager.GetString("Backups_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create backup, because directory for save games is missed {0}..
        /// </summary>
        public static string Can_t_create_backup__because_directory_for_save_games_is_missed__0__ {
            get {
                return ResourceManager.GetString("Can\'t create backup, because directory for save games is missed {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create backup, because no file was found in directory &apos;{0}&apos;..
        /// </summary>
        public static string Can_t_create_backup__because_no_file_was_found_in_directory___0___ {
            get {
                return ResourceManager.GetString("Can\'t create backup, because no file was found in directory \'{0}\'.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create backup, because path &apos;{0}&apos; of job &apos;{1}&apos; can&apos;t be found..
        /// </summary>
        public static string Can_t_create_backup__because_path___0___of_job___1___can_t_be_found_ {
            get {
                return ResourceManager.GetString("Can\'t create backup, because path \'{0}\' of job \'{1}\' can\'t be found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        public static string Create_Backup {
            get {
                return ResourceManager.GetString("Create_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new backup job.
        /// </summary>
        public static string Create_new_backup_job {
            get {
                return ResourceManager.GetString("Create_new_backup_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected backup job?.
        /// </summary>
        public static string Delete_selected_backup_job_ {
            get {
                return ResourceManager.GetString("Delete selected backup job?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include local Valheim save games in Backups.
        /// </summary>
        public static string Include_local_Valheim_save_games_in_Backups {
            get {
                return ResourceManager.GetString("Include_local_Valheim_save_games_in_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included.
        /// </summary>
        public static string Included {
            get {
                return ResourceManager.GetString("Included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2021 Bernhard Strathewerd
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenceTxt {
            get {
                return ResourceManager.GetString("LicenceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup can be created because no data to be backed up is defined..
        /// </summary>
        public static string No_backup_can_be_created_because_no_data_to_be_backed_up_is_defined {
            get {
                return ResourceManager.GetString("No backup can be created because no data to be backed up is defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only unique non-empty names are allowed for backup jobs..
        /// </summary>
        public static string Only_unique_non_empty_names_are_allowed_for_backup_jobs_ {
            get {
                return ResourceManager.GetString("Only unique non-empty names are allowed for backup jobs.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open archiving path.
        /// </summary>
        public static string Open_archiving_path {
            get {
                return ResourceManager.GetString("Open_archiving_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Valheim save games path.
        /// </summary>
        public static string Open_Valheim_save_games_path {
            get {
                return ResourceManager.GetString("Open_Valheim_save_games_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to backup.
        /// </summary>
        public static string Path_to_backup {
            get {
                return ResourceManager.GetString("Path_to_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select archiving path.
        /// </summary>
        public static string Select_archiving_path {
            get {
                return ResourceManager.GetString("Select archiving path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path.
        /// </summary>
        public static string Select_path {
            get {
                return ResourceManager.GetString("Select_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default path.
        /// </summary>
        public static string Set_default_path {
            get {
                return ResourceManager.GetString("Set_default_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon VBackupManager {
            get {
                object obj = ResourceManager.GetObject("VBackupManager", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
